accounts/urls.py
from django.conf import settings
from django.urls import include, path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.profile_edit, name='profile_edit'),
    path('password_change/', views.password_change, name='password_change'),
]

django_react_ver2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django_pydenticon.views import image as pydenticon_image


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('identicon/image/<path:data>/', pydenticon_image, name='pydenticon_image'),
    path('feeds/', include('feeds.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

feeds/urls.py
from django.conf import settings
from django.urls import include, path

from . import views

app_name = 'feeds'

urlpatterns = [
    path('post/', views.post_new, name='post'),
    path('detail/<int:pk>/', views.post_detail, name='post_detail'),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.core.validators import RegexValidator
from django.template.loader import render_to_string
from django.shortcuts import resolve_url

# Create your models here.
class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = 'M', '남성'
        FEMALE = 'F', '여성'

    website_url = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    phone_number = models.CharField(max_length=13, blank=True,
                                    validators=[RegexValidator(r'^010-?\d{4}-?\d{4}')])
    gender = models.CharField(max_length=1, blank=True, choices=GenderChoices.choices)
    avatar = models.ImageField(blank=True, upload_to='accounts/profile/%Y/%m/%d',
                                help_text='48px * 48px 크기의 png/jpeg를 업로드 해 주세요.')
    @property
    def name(self):
        return self.username
    
    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        else:
            return resolve_url('pydenticon_image', self.username)

    def send_welcome_email(self):
        subject = render_to_string('accounts/welcome_email_subject.txt', {
            'user': self,
        })
        content = render_to_string('accounts/welcome_email_content.txt', {
            'user': self,
        })
        sender_email = settings.WELCOME_EMAIL_SENDER
        send_mail(subject, content, sender_email, [self.website_url], fail_silently=False)

feeds/models.py
import re

from django.urls import reverse
from django.db import models
from django.conf import settings

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='feeds/post/%Y/%m/%d')
    caption = models.CharField(max_length=500)
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.caption
    
    def extract_tag_list(self):
        tag_list = []
        for tag_name in re.findall(r'#([a-zA-Zㄱ-힣]+)', self.caption):
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        
        return tag_list
    
    def get_absolute_url(self):
        return reverse('feeds:post_detail', args=[self.pk])

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, PasswordChangeForm as AuthPasswordChangeForm,
)

from .models import User

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['avatar', 'username', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError('이미 등록된 이메일 주소입니다.')
            return email
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'username', 'email', 'phone_number', 'gender']

class PasswordChangeForm(AuthPasswordChangeForm):
    def clean_new_password2(self):
        old_password = self.clean_old_password()
        new_password2 = super().clean_new_password2()

        if old_password == new_password2:
            raise forms.ValidationError('새로운 암호는 기존 암호와 다르게 입력해주세요.')
        return new_password2

feeds/forms.py
from django import forms
from django.forms import widgets

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location']
        widgets = {
            'caption': forms.Textarea,
        }

accounts/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, logout_then_login, 
    PasswordChangeView as AuthPasswordChangeView,
)

from .forms import (
    PasswordChangeForm, ProfileForm, SignupForm,
)

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            signed_user = form.save()
            signed_user.send_welcome_email() # FIXME: Celery로 처리하기
            auth_login(request, signed_user)
            messages.success(request, '회원가입이 완료되었습니다.')
            return redirect('root')
    else:
        form = SignupForm()
    
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })

login = LoginView.as_view(template_name='accounts/login_form.html')

def logout(request):
    messages.success(request, '로그아웃이 되었습니다.')
    return logout_then_login(request)

@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, '프로필 수정이 완료되었습니다.')
            return redirect('accounts:profile_edit')
    else:
        form = ProfileForm(instance=request.user)

    return render(request, 'accounts/profile_edit.html', {
        'form': form,
    })

class PasswordChangeView(LoginRequiredMixin, AuthPasswordChangeView):
    success_url = reverse_lazy('accounts:password_change')
    template_name = 'accounts/password_change_form.html'
    form_class = PasswordChangeForm

    def form_valid(self, form):
        messages.success(self.request, '암호를 변경했습니다.')
        return super().form_valid(form)

password_change = PasswordChangeView.as_view()

feeds/views.py
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Post, Tag
from .forms import PostForm

# Create your views here.
@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, '새 포스팅이 저장되었습니다.')
            return redirect(post)
    else:
        form = PostForm()

    return render(request, 'feeds/post_new_form.html', {
        'form': form,
    })

def post_detail(request, pk):
    try:
        post = get_object_or_404(Post, pk=pk)
    except Post.DoesNotExist:
        raise Http404('해당 모델이 존재하지 않습니다.')

    return render(request, 'feeds/post_detail.html', {
        'post': post,
    })

accounts/templates/accounts/login_form.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
    {% include "_form.html" with form_title="로그인" submit_label="로그인" %}
{% endblock content %}

accounts/templates/accounts/password_change_form.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
    {% include "_form.html" with form_title="암호변경" submit_label="암호변경" %}
{% endblock content %}

accounts/templates/accounts/profile_edit.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
    {% include "_form.html" with form_title="프로필 수정" submit_label="프로필 수정" %}
{% endblock content %}

accounts/templates/accounts/signup_form.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
    {% include "_form.html" with submit_label="회원가입" %}
{% endblock content %}

django_react_ver2/templates/_form.html
{% load bootstrap4 %}

<div class="container my-3">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <div class="card">
                {% if form_title %}
                    <div class="card-header">
                        {{ form_title }}
                    </div>
                {% endif %}
                <div class="card-body">
                    {% if form %}
                        <form action="" enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" value="{{ submit_label|default:'Submit' }}" class="btn btn-primary">
                        </form>
                    {% else %}
                        <div class="alert alert-danger">
                            form 객체를 지정해 주세요.
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

django_react_ver2/templates/footer.html
<div class="border-top">
    <div class="container">
        <div class="my-md-5">
            <div class="row">
              <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">© 2021</small>
              </div>
              <div class="col-6 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                  <li><a class="text-muted" href="#">Cool stuff</a></li>
                  <li><a class="text-muted" href="#">Random feature</a></li>
                  <li><a class="text-muted" href="#">Team feature</a></li>
                  <li><a class="text-muted" href="#">Stuff for developers</a></li>
                  <li><a class="text-muted" href="#">Another one</a></li>
                  <li><a class="text-muted" href="#">Last time</a></li>
                </ul>
              </div>
              <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                  <li><a class="text-muted" href="#">Resource</a></li>
                  <li><a class="text-muted" href="#">Resource name</a></li>
                  <li><a class="text-muted" href="#">Another resource</a></li>
                  <li><a class="text-muted" href="#">Final resource</a></li>
                </ul>
              </div>
              <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                  <li><a class="text-muted" href="#">Team</a></li>
                  <li><a class="text-muted" href="#">Locations</a></li>
                  <li><a class="text-muted" href="#">Privacy</a></li>
                  <li><a class="text-muted" href="#">Terms</a></li>
                </ul>
              </div>
            </div>
        </div>
    </div>
</div>

django_react_ver2/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Instagram</title>
  
    <link rel="stylesheet" href="{% static 'bootstrap-4.6.1-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.6.1-dist/js/bootstrap.min.js' %}"></script>
  
    <style>
      @font-face {
          font-family: 'NanumSquareB';
          src: local('NanumSquareB'),
          url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype")
      }
      @font-face {
          font-family: 'NanumSquareEB';
          src: local('NanumSquareEB'),
          url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype")
      }
      @font-face {
          font-family: 'NanumSquareL';
          src: local('NanumSquareL'),
          url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype")
      }
      @font-face {
          font-family: 'NanumSquareR';
          src: local('NanumSquareR'),
          url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype")
      }
    </style>
  </head>

django_react_ver2/templates/header.html
<div class="border-bottom">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white">
                    <h5 class="my-0 mr-md-auto font-weight-normal">
                        SNS prototype
                    </h5>
                    <nav class="my-2 my-md-0 mr-md-3">
                      {% if user.is_authenticated %}
                        <img src="{{ user.avatar_url }}" class="rounded-circle" style="width: 2rem; height: 2rem;">
                        <a class="p-2 text-dark" href="{% url 'accounts:profile_edit' %}">프로필</a>
                      {% else %}
                        <a class="p-2 text-dark" href="{% url 'accounts:login' %}">로그인</a>
                      {% endif %}
                    </nav>
                    {% if user.is_authenticated %}
                      <a class="btn btn-outline-primary" href="{% url 'accounts:logout' %}">로그아웃</a>
                    {% else %}
                      <a class="btn btn-outline-primary" href="{% url 'accounts:signup' %}">회원가입</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

django_react_ver2/templates/layout.html
<!DOCTYPE html>
<html lang="ko">

{% include "head.html" %}

<body style="font-family: 'NanumSquareR';">

<div>
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
</div>

{% include "header.html" %}

{% block content %}
{% endblock %}

{% include "footer.html" %}

</body>
</html>

django_react_ver2/templates/root.html
{% extends "layout.html" %}

{% block content %}
    <div class="container my-4">
        <div class="row"> 
            <div class="col-sm-12">
                <h4>
                    테스트
                </h1>
                <hr />
                <a href="{% url 'feeds:post' %}" class="btn btn-primary">
                    새 포스팅
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

feeds/templates/feeds/post_detail.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <div class="card">
                <div class="card-header">
                    <img src="{{ post.author.avatar_url }}" class="rounded-circle" style="width: 2rem; height: 2rem;">
                    {{ post.author.name }}
                </div>
                <div class="card-body">
                    <img src="{{ post.photo.url }}" style="width: 10rem; height: 10rem;">
                    <div>
                        {{ post.caption }}
                    </div>
                </div>
                <div class="card-footer">
                    {% for tag_name in post.tag_set.all %}
                        <span class="badge badge-primary">
                            {{ tag_name }} 
                        </span>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

feeds/templates/feeds/post_new_form.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
    {% include "_form.html" with form_title="포스팅" submit_label="완료" %}
{% endblock content %}